# Setting important variables for reference later.
variables:
  - name: DOCKER_BUILDKIT
    value: "1"
  - name: COMPOSE_DOCKER_CLI_BUILD
    value: "1"
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

# This means everytime a commit is made on the main branch the pipeline will trigger.
trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - prototype/

# This means you have to PR a branch to trigger the pipeline.
pr:
  branches:
    include:
      - "*"

# Using latest Ubuntu image.
pool:
  vmImage: "ubuntu-latest"

stages:
  - jobs:
      - job: Build_backend
        displayName: "Build backend"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 18.x

          - task: Npm@1
            displayName: "NPM install"
            inputs:
              command: "custom"
              customCommand: "ci"
              workingDir: $(Build.SourcesDirectory)/src/core

          - task: Npm@1
            displayName: "Check types"
            inputs:
              commands: "custom"
              customCommand: "run check-types"
              workingDir: $(Build.SourcesDirectory)/src/core

          - task: Npm@1
            displayName: "Test"
            inputs:
              command: "custom"
              customCommand: "run test -- --watchAll=false"
              workingDir: $(Build.SourcesDirectory)/src/core

          - task: Npm@1
            displayName: "Build"
            inputs:
              command: "custom"
              customCommand: "run build"
              workingDir: $(Build.SourcesDirectory)/src/core

          - publish: "$(Build.SourcesDirectory)/src/core/build"
            displayName: "Publish backend build files"
            artifact: backend

      - job: Build_frontend
        displayName: "Build frontend"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 18.x
