variables:
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isVersionTag
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/v')]
  - name: core-dockerRepository
    value: bobby1072/fs2_docker_image

trigger:
  branches:
    include:
      - main

# pr:
#   branches:
#     include:
#       - "*"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    jobs:
      - job: Build_frontend
        displayName: "Build frontend"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 20.x
          - task: Npm@1
            displayName: "NPM install"
            inputs:
              command: "custom"
              customCommand: "ci"
              workingDir: $(Build.SourcesDirectory)/src/client

          - task: Npm@1
            displayName: "Check types"
            inputs:
              commands: "custom"
              customCommand: "run check-types"
              workingDir: $(Build.SourcesDirectory)/src/client

          - powershell: $(Build.SourcesDirectory)/build-scripts/add_build_env_frontend.ps1
            displayName: "Add build environment"

          - task: Npm@1
            displayName: "Build"
            inputs:
              command: "custom"
              customCommand: "run build"
              workingDir: $(Build.SourcesDirectory)/src/client

          - publish: "$(Build.SourcesDirectory)/src/client/build"
            displayName: "Publish client files"
            artifact: client

  - stage: Publish
    condition: and(succeeded(), eq(variables.isVersionTag, true), eq(variables.isMain, true))
    jobs:
      - job: push_core_image
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: client
              path: $(Build.SourcesDirectory)/src/client/build

          - task: Bash@3
            displayName: Get Image Tag
            inputs:
              targetType: "inline"
              script: |
                TAG=$(git tag -l v* --sort=-creatordate | head -n 1)
                echo "##vso[task.setvariable variable=ImageTag]$TAG"
              workingDirectory: "$(Build.SourcesDirectory)"

          - task: Docker@2
            displayName: Login to Docker Hub
            inputs:
              command: login
              containerRegistry: DockerHub
              username: $(dockerHubUsername)
              password: $(dockerHubPassword)

          - task: Docker@2
            displayName: Build Core Image
            inputs:
              command: build
              repository: $(core-dockerRepository)
              tags: |
                latest
                $(ImageTag)
              Dockerfile: "$(Build.SourcesDirectory)/src/fsCore/dockerfile"
              buildContext: "$(Build.SourcesDirectory)"
              arguments: --build-arg WEB_APP_CLIENT_PATH=src/client/build/

          - task: Docker@2
            displayName: Push Core Image
            inputs:
              command: push
              repository: $(core-dockerRepository)
              tags: |
                latest
                $(ImageTag)
