version: "3.8"

volumes:
  postgres_data: {}

services:
  postgres:
    container_name: fs.db
    image: postgres:15-alpine
    ports:
      - 5560:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./src/core/src/persistence/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_DB: fs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
